### ISSUE TITLE
googleads v9?

### ISSUE THREAD

**Issue by scotthenley** [dictav/go-genproto-googleads#1]
Hi, I have been using this project successfully in some production services. I noticed it has not been updated with v9 of the Ads API. I tried following your patched Bazel files to cover v9 but I am running into protoc errors when building. Just curious if you have attempted building v9 from the google protobuf files and if you also ran into any issues? Fingers crossed Google decides to release an official Go library in 2022.

**Comment by dictav** [comment]
Hi,

I'll try building v9 this weekend.

**Comment by dictav** [comment]
https://github.com/dictav/go-genproto-googleads/releases/tag/v0.20220116.1
